services:
  ros2:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: olegmilantiev/docker-ros2-nvidia:cuda12.2.2-ubuntu22.04-ros2_iron
    image: olegmilantiev/docker-ros2-nvidia:cuda12.6.3-ubuntu24.04-ros2_jazzy
    container_name: ros2
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /ros2-vedrus:/ros2-vedrus
      - /dev:/dev
    tty: true
    working_dir: /ros2-vedrus
